### ISSUE TITLE
Error in 1.8.8

### ISSUE THREAD

**Issue by MinecheckerHD** [TheLimeGlass/Beamer#3]
I've got an error by using just the example of the plugin.
Skript Version: 2.2-SNAPSHOT
Server Version: Spigot 1.8.8

Please help me and fix it.

Here is the skript:

command /beam:
	trigger:
		set {_beam} to a new beam between player and target block for player
		start beam {_beam}
		wait 5 seconds
		stop beam {_beam}
		broadcast "stopping"

And I get this error:

[23:58:05 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.2-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:376) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:363) ~[?:?]
        at me.limeglass.beamer.protocol.PacketFactory_1_8_R1.createPacketSquidSpawn(PacketFactory_1_8_R1.java:64) ~[?:?]
        at me.limeglass.beamer.protocol.beam.LocationTargetBeam.<init>(LocationTargetBeam.java:55) ~[?:?]
        at me.limeglass.beamer.protocol.beam.Beam.<init>(Beam.java:58) ~[?:?]
        at me.limeglass.beamer.protocol.beam.ClientBeam.<init>(ClientBeam.java:30) ~[?:?]
        at me.limeglass.beamer.protocol.beam.ClientBeam.<init>(ClientBeam.java:26) ~[?:?]
        at me.limeglass.beamer.elements.expressions.ExprNewClientBeam.get(ExprNewClientBeam.java:32) ~[?:?]
        at me.limeglass.beamer.elements.expressions.ExprNewClientBeam.get(ExprNewClientBeam.java:16) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:270) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:269) ~[?:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:164) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        ... 16 more
[23:58:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'beam' in plugin Skript v2.2-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:376) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:363) ~[?:?]
        at me.limeglass.beamer.protocol.PacketFactory_1_8_R1.createPacketSquidSpawn(PacketFactory_1_8_R1.java:64) ~[?:?]
        at me.limeglass.beamer.protocol.beam.LocationTargetBeam.<init>(LocationTargetBeam.java:55) ~[?:?]
        at me.limeglass.beamer.protocol.beam.Beam.<init>(Beam.java:58) ~[?:?]
        at me.limeglass.beamer.protocol.beam.ClientBeam.<init>(ClientBeam.java:30) ~[?:?]
        at me.limeglass.beamer.protocol.beam.ClientBeam.<init>(ClientBeam.java:26) ~[?:?]
        at me.limeglass.beamer.elements.expressions.ExprNewClientBeam.get(ExprNewClientBeam.java:32) ~[?:?]
        at me.limeglass.beamer.elements.expressions.ExprNewClientBeam.get(ExprNewClientBeam.java:16) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:270) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:161) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more

**Comment by TheLimeGlass** [comment]
What version of ProtocolLib are you using? Make sure you're using the correct version of ProtocolLib for your server!

**Comment by MinecheckerHD** [comment]
Hello TheLimeGlass, 

I'm using ProtocolLib version 4.0.2

If this is not the correct version, then please tell me the right one.

~MinecheckerHD

**Comment by MinecheckerHD** [comment]
If you need Amy other Information, just ask. :)

**Comment by MinecheckerHD** [comment]
Hello TheLimeGlass,

I found the problem, but I have two question:
- How can the beam follow a player? I want that the beam follows the player when he is moving.
- And how can I spawn more than one beam at the same time?

Thanks for reading!

~MinecheckerHD

**Comment by TheLimeGlass** [comment]
What was the issue? You just create more with the syntax by using it again, and you set the end location to the player and update the beam.

**Comment by MinecheckerHD** [comment]
Hello TheLimeGlass,

I've just set up a new server and put all the plugins on it like on the server where I have tested it before. And there it now works perfectly! (I think it was because the server I used before was over 2 jears old)

And I've tried to update it. But it didn't worked.
For you to understand: I want to make a animation and for that the beam must follow the player constantly.

Here is a little part of the skript:

command /beam <player>:
	trigger:
		loop all entities in radius 10 of arg-1:
			name of loop-entity is "TEST":
				set {_Loc} to location of loop-entity
				set {_B1} to a new global beam from {_Loc} to arg 1 in radius 20 and update delay 1
				start beam {_B1}
				wait 1 tick
				update beam {_B1}
                                wait 1 tick
                                update beam {_B1}
                                #and so on...
				wait 15 seconds
				stop beam {_B1}

Have a nice day!

~MinecheckerHD
